title: Hello, Chan Dinh
author:
  name: Chan Dinh
  email: dinhhoangbaochan@gmail.com
description: >
  Where I write all my research, notes or simply rants about
  everything that I don't like.
theme: minima
